/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTicketsRouteImport } from './routes/_app/tickets'
import { Route as AppStaffRouteImport } from './routes/_app/staff'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as NameTokenRouteImport } from './routes/$name.$token'
import { Route as AppClubManagementIndexRouteImport } from './routes/_app/club-management/index'
import { Route as AppClubManagementNewRouteImport } from './routes/_app/club-management/new'
import { Route as AppClubManagementDocumentIdEditRouteImport } from './routes/_app/club-management/$documentId/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const NameTokenRoute = NameTokenRouteImport.update({
  id: '/$name/$token',
  path: '/$name/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClubManagementIndexRoute = AppClubManagementIndexRouteImport.update({
  id: '/club-management/',
  path: '/club-management/',
  getParentRoute: () => AppRoute,
} as any)
const AppClubManagementNewRoute = AppClubManagementNewRouteImport.update({
  id: '/club-management/new',
  path: '/club-management/new',
  getParentRoute: () => AppRoute,
} as any)
const AppClubManagementDocumentIdEditRoute =
  AppClubManagementDocumentIdEditRouteImport.update({
    id: '/club-management/$documentId/edit',
    path: '/club-management/$documentId/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$name/$token': typeof NameTokenRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/tickets': typeof AppTicketsRoute
  '/club-management/new': typeof AppClubManagementNewRoute
  '/club-management/': typeof AppClubManagementIndexRoute
  '/club-management/$documentId/edit': typeof AppClubManagementDocumentIdEditRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$name/$token': typeof NameTokenRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/tickets': typeof AppTicketsRoute
  '/': typeof AppIndexRoute
  '/club-management/new': typeof AppClubManagementNewRoute
  '/club-management': typeof AppClubManagementIndexRoute
  '/club-management/$documentId/edit': typeof AppClubManagementDocumentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/$name/$token': typeof NameTokenRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/tickets': typeof AppTicketsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/club-management/new': typeof AppClubManagementNewRoute
  '/_app/club-management/': typeof AppClubManagementIndexRoute
  '/_app/club-management/$documentId/edit': typeof AppClubManagementDocumentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/$name/$token'
    | '/dashboard'
    | '/settings'
    | '/staff'
    | '/tickets'
    | '/club-management/new'
    | '/club-management/'
    | '/club-management/$documentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/$name/$token'
    | '/dashboard'
    | '/settings'
    | '/staff'
    | '/tickets'
    | '/'
    | '/club-management/new'
    | '/club-management'
    | '/club-management/$documentId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/$name/$token'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/staff'
    | '/_app/tickets'
    | '/_app/'
    | '/_app/club-management/new'
    | '/_app/club-management/'
    | '/_app/club-management/$documentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  NameTokenRoute: typeof NameTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/$name/$token': {
      id: '/$name/$token'
      path: '/$name/$token'
      fullPath: '/$name/$token'
      preLoaderRoute: typeof NameTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/club-management/': {
      id: '/_app/club-management/'
      path: '/club-management'
      fullPath: '/club-management/'
      preLoaderRoute: typeof AppClubManagementIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/club-management/new': {
      id: '/_app/club-management/new'
      path: '/club-management/new'
      fullPath: '/club-management/new'
      preLoaderRoute: typeof AppClubManagementNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/club-management/$documentId/edit': {
      id: '/_app/club-management/$documentId/edit'
      path: '/club-management/$documentId/edit'
      fullPath: '/club-management/$documentId/edit'
      preLoaderRoute: typeof AppClubManagementDocumentIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppTicketsRoute: typeof AppTicketsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClubManagementNewRoute: typeof AppClubManagementNewRoute
  AppClubManagementIndexRoute: typeof AppClubManagementIndexRoute
  AppClubManagementDocumentIdEditRoute: typeof AppClubManagementDocumentIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppTicketsRoute: AppTicketsRoute,
  AppIndexRoute: AppIndexRoute,
  AppClubManagementNewRoute: AppClubManagementNewRoute,
  AppClubManagementIndexRoute: AppClubManagementIndexRoute,
  AppClubManagementDocumentIdEditRoute: AppClubManagementDocumentIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  NameTokenRoute: NameTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
