export const INVITATION_MESSAGE = {
  INVITER_NOT_FOUND: 'Propietario no encontrado',
  CLUB_NOT_FOUND: 'Club no encontrado',
  EMAIL_ALREADY_REGISTERED: 'Este correo ya está registrado.',
  FORBIDDEN: 'Solo un propietario puede crear invitaciones.',
  CREATE_FAILED: 'No se pudo crear la invitación',
  LIST_FAILED: 'No se pudo listar las invitaciones',
  NOT_FOUND: 'Invitación no encontrada',
  DELETE_ACCEPTED: 'No se puede eliminar una invitación ya aceptada.',
  DELETE_FAILED: 'No se pudo eliminar la invitación',
  PUBLIC_INVALID: 'El enlace de invitación no es válido.',
  PUBLIC_SLUG_MISMATCH: 'El enlace de invitación no coincide.',
  PUBLIC_EXPIRED: 'El enlace de invitación expiró.',
  PUBLIC_ALREADY_ACCEPTED: 'Esta invitación ya fue aceptada.',
  PUBLIC_GET_FAILED: 'No se pudo obtener la invitación',
  SECURITY_WORD_INVALID: 'La palabra de seguridad es incorrecta.',
  ACCEPT_SUCCESS: 'Cuenta creada. Ya podés iniciar sesión.',
  ACCEPT_FAILED: 'No se pudo crear la cuenta. Intentá de nuevo.',
} as const
